2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:50:43,626 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-18 18:51:49,177 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 78, in login
    email = request.form['email']
            ~~~~~~~~~~~~^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\werkzeug\datastructures\structures.py", line 196, in __getitem__
    raise exceptions.BadRequestKeyError(key)
werkzeug.exceptions.BadRequestKeyError: 400 Bad Request: The browser (or proxy) sent a request that this server could not understand.

2024-08-19 13:44:49,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:44:49,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:47:08,281 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:47:08,281 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:47:18,134 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:47:18,134 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:47:18,134 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:50:02,634 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:50:02,634 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:50:21,283 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:50:21,283 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:50:21,283 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 90, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-08-19 13:52:36,609 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:52:36,609 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:52:46,272 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:52:46,272 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:52:46,272 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:53:22,537 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:53:22,537 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:55:30,929 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:55:30,929 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:57:18,869 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-08-19 13:57:18,869 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 84, in login
    state.active_account = svc.find_account_by_email(email)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 23, in find_account_by_email
    owner = Owner.objects(email=email).first()
            ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\manager.py", line 38, in __get__
    queryset = queryset_class(owner, owner._get_collection())
                                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 224, in _get_collection
    db = cls._get_db()
         ^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 202, in _get_db
    return get_db(cls._meta.get("db_alias", DEFAULT_CONNECTION_NAME))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 415, in get_db
    conn = get_connection(alias)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\connection.py", line 317, in get_connection
    raise ConnectionFailure(msg)
mongoengine.connection.ConnectionFailure: Connection with alias "core" has not been defined

2024-11-08 14:35:10,910 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 14:35:10,910 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 14:38:17,129 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 14:38:17,129 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 14:49:56,651 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 14:49:56,651 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 15:01:08,784 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 15:01:08,784 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 15:41:53,321 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 127, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 15:41:53,321 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 127, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 15:41:53,321 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 127, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:16:55,523 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:16:55,523 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:18:40,176 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:18:40,176 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:10,867 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:10,867 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:10,867 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:38,485 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:38,485 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:38,485 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:19:38,485 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:20:53,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:20:53,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:20:53,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:20:53,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:20:53,863 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:22:43,739 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:22:43,739 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:26:35,200 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    print(f"Logged in as: {state.active_account.id}")
                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:26:35,200 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 124, in login
    print(f"Logged in as: {state.active_account.id}")
                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:27:25,684 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 125, in login
    print(f"Logged in as: {state.active_account.id}")
                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:27:25,684 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 125, in login
    print(f"Logged in as: {state.active_account.id}")
                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:28:04,999 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 125, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:28:04,999 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 125, in login
    print(state.active_account.id)
          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:28:37,333 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:28:37,333 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:32:09,677 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:32:09,677 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:02,601 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:02,601 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 126, in login
    app.logger.info(f"Logged in as guest: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:49,260 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 129, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:49,260 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 129, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:49,260 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 129, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:49,260 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 129, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-08 18:35:49,260 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 129, in login
    app.logger.info(f"Logged in as host: {state.active_account.id}")
                                          ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-19 16:43:25,945 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 140, in login
    app.logger.info(f"Logged in as admin: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-19 16:43:25,945 - ERROR - Error in login_route: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 140, in login
    app.logger.info(f"Logged in as admin: {state.active_account.id}")
                                           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'

2024-11-20 14:26:31,953 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 302, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:26:49,347 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 302, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:26:49,347 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 302, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:29:44,511 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 302, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:29:44,511 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 302, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:32:28,704 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-20 14:32:28,704 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:21:31,892 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:21:31,892 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 283, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:22:46,114 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:22:46,114 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:23:40,604 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:23:40,604 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 305, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:26:45,548 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 306, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:26:45,548 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 306, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:34:26,399 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 306, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:34:26,399 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 306, in get_all_bookings
    return Booking.objects.all()
           ^^^^^^^^^^^^^^^
AttributeError: type object 'Booking' has no attribute 'objects'

2024-11-21 11:48:29,301 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 308, in get_all_bookings
    for kennel in kennels:
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 109, in _iter_results
    self._populate_cache()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 128, in _populate_cache
    self._result_cache.append(next(self))
                              ^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\base.py", line 1634, in __next__
    doc = self._document._from_son(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 815, in _from_son
    value if value is None else field.to_python(value)
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\fields.py", line 380, in to_python
    key: self.field.to_python(item) for key, item in value.items()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\fields.py", line 744, in to_python
    return self.document_type._from_son(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 834, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 90, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'rating'}" do not exist on the document "Booking"

2024-11-21 11:48:29,301 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 284, in analytics_dashboard
    bookings = svc.get_all_bookings()
               ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 308, in get_all_bookings
    for kennel in kennels:
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 109, in _iter_results
    self._populate_cache()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\queryset.py", line 128, in _populate_cache
    self._result_cache.append(next(self))
                              ^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\queryset\base.py", line 1634, in __next__
    doc = self._document._from_son(
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 815, in _from_son
    value if value is None else field.to_python(value)
                                ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\fields.py", line 380, in to_python
    key: self.field.to_python(item) for key, item in value.items()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\fields.py", line 744, in to_python
    return self.document_type._from_son(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 834, in _from_son
    obj = cls(__auto_convert=False, _created=created, **data)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\document.py", line 90, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\mongoengine\base\document.py", line 99, in __init__
    raise FieldDoesNotExist(msg)
mongoengine.errors.FieldDoesNotExist: The fields "{'rating'}" do not exist on the document "Booking"

2024-11-21 11:49:37,048 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 330, in get_kennel_usage_data
    kennel_usage[booking.kennel.id] += 1
                 ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 11:49:37,048 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 330, in get_kennel_usage_data
    kennel_usage[booking.kennel.id] += 1
                 ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 11:54:37,651 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 333, in get_kennel_usage_data
    if booking.kennel:
       ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 11:54:37,651 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 333, in get_kennel_usage_data
    if booking.kennel:
       ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 13:31:52,437 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 333, in get_kennel_usage_data
    if booking.kennel:
       ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 13:31:52,437 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    kennel_usage = svc.get_kennel_usage_data(bookings, kennels)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 333, in get_kennel_usage_data
    if booking.kennel:
       ^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2024-11-21 13:37:55,727 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 345, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2024-11-21 13:37:55,727 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 345, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2024-11-21 13:40:17,351 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 343, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2024-11-21 13:40:17,351 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 343, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:22:06,107 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 343, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:22:06,107 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 292, in analytics_dashboard
    booking_trends = svc.get_booking_trends(bookings)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 343, in get_booking_trends
    data = [(b.check_in_date, b.check_out_date) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:36:35,771 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'services.data_service' has no attribute 'get_kennel_occupancy'

2025-01-07 19:36:35,771 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'services.data_service' has no attribute 'get_kennel_occupancy'

2025-01-07 19:39:52,540 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 367, in get_kennel_occupancy
    data = [(b.kennel.id, b.check_in_date, b.check_out_date) for b in bookings if b.kennel.id in kennel_ids]
                                                                                  ^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2025-01-07 19:39:52,540 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 367, in get_kennel_occupancy
    data = [(b.kennel.id, b.check_in_date, b.check_out_date) for b in bookings if b.kennel.id in kennel_ids]
                                                                                  ^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2025-01-07 19:44:06,170 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 367, in get_kennel_occupancy
    data = [(b.kennel.id, b.duration_in_days) for b in bookings if b.kennel]
                                                                   ^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2025-01-07 19:44:06,170 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 367, in get_kennel_occupancy
    data = [(b.kennel.id, b.duration_in_days) for b in bookings if b.kennel]
                                                                   ^^^^^^^^
AttributeError: 'dict' object has no attribute 'kennel'

2025-01-07 19:47:02,603 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 388, in get_kennel_occupancy
    kennel_occupancy.plot(kind='pie', ax=ax, autopct='%1.1f%%', startangle=90, colormap='Set3')
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_core.py", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 499, in generate
    self._compute_plot_data()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 698, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot

2025-01-07 19:47:02,603 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 388, in get_kennel_occupancy
    kennel_occupancy.plot(kind='pie', ax=ax, autopct='%1.1f%%', startangle=90, colormap='Set3')
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_core.py", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 499, in generate
    self._compute_plot_data()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 698, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot

2025-01-07 19:47:19,686 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 293, in analytics_dashboard
    plot_data = svc.get_average_booking_duration(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 406, in get_average_booking_duration
    data = [(b.check_in_date, b.duration_in_days) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:47:19,686 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 293, in analytics_dashboard
    plot_data = svc.get_average_booking_duration(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 406, in get_average_booking_duration
    data = [(b.check_in_date, b.duration_in_days) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:47:21,703 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 295, in analytics_dashboard
    plot_data = svc.get_monthly_revenue(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 431, in get_monthly_revenue
    data = [(b.check_in_date, b.duration_in_days * 50) for b in bookings]  # Replace 50 with actual rate/day
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:47:21,703 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 295, in analytics_dashboard
    plot_data = svc.get_monthly_revenue(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 431, in get_monthly_revenue
    data = [(b.check_in_date, b.duration_in_days * 50) for b in bookings]  # Replace 50 with actual rate/day
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:47:32,380 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 293, in analytics_dashboard
    plot_data = svc.get_average_booking_duration(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 406, in get_average_booking_duration
    data = [(b.check_in_date, b.duration_in_days) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:47:32,380 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 293, in analytics_dashboard
    plot_data = svc.get_average_booking_duration(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 406, in get_average_booking_duration
    data = [(b.check_in_date, b.duration_in_days) for b in bookings]
             ^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'check_in_date'

2025-01-07 19:49:11,397 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 295, in analytics_dashboard
    plot_data = svc.get_monthly_revenue(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 431, in get_monthly_revenue
    data = [(b['check_in_date'], b['duration_in_days'] * 50) for b in bookings]  # Replace 50 with actual rate/day
                                 ~^^^^^^^^^^^^^^^^^^^^
KeyError: 'duration_in_days'

2025-01-07 19:49:11,397 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 295, in analytics_dashboard
    plot_data = svc.get_monthly_revenue(bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 431, in get_monthly_revenue
    data = [(b['check_in_date'], b['duration_in_days'] * 50) for b in bookings]  # Replace 50 with actual rate/day
                                 ~^^^^^^^^^^^^^^^^^^^^
KeyError: 'duration_in_days'

2025-01-08 13:19:45,323 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 388, in get_kennel_occupancy
    kennel_occupancy.plot(kind='pie', ax=ax, autopct='%1.1f%%', startangle=90, colormap='Set3')
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_core.py", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 499, in generate
    self._compute_plot_data()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 698, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot

2025-01-08 13:19:45,323 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 291, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\services\data_service.py", line 388, in get_kennel_occupancy
    kennel_occupancy.plot(kind='pie', ax=ax, autopct='%1.1f%%', startangle=90, colormap='Set3')
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_core.py", line 1030, in __call__
    return plot_backend.plot(data, kind=kind, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\__init__.py", line 71, in plot
    plot_obj.generate()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 499, in generate
    self._compute_plot_data()
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\venv\Lib\site-packages\pandas\plotting\_matplotlib\core.py", line 698, in _compute_plot_data
    raise TypeError("no numeric data to plot")
TypeError: no numeric data to plot

2025-01-08 14:11:54,958 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 297, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_kennel_occupancy() takes 1 positional argument but 2 were given

2025-01-08 14:11:54,958 - ERROR - Error loading analytics dashboard: Traceback (most recent call last):
  File "C:\Users\revat\Documents\mongodb-quickstart-course\src\snake_bnb\src\app.py", line 297, in analytics_dashboard
    plot_data = svc.get_kennel_occupancy(kennels, bookings)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: get_kennel_occupancy() takes 1 positional argument but 2 were given

